### ISSUE TITLE
Completing Assignment C Part 2

### ISSUE THREAD

**Issue by Emora21** [IntroToCode/CodeMates11_Fall22#4]
## 💬 Discussion topic

Include two delicious recipes by filling out all the required fields as stated in the assignment.

## ❗ Potential issues

Make sure we are thorough and includes equipment, instructions, ingredients needed, etc.

## 👥 People to consult

[@Weisgit](https://github.com/Weisgit) [@D4V1DT4YL0R](https://github.com/D4V1DT4YL0R) [@ngocnguyen-angie](https://github.com/ngocnguyen-angie) [@Emora21](https://github.com/Emora21) [@TomPerticucci](https://github.com/TomPerticucci)

## 📃 Details

Your Codemates team used Issues to clearly delineate work (30%)
Was there stated acceptance criteria?
Were ideas communicated, debated, and resolved in the Pull Requests?
Have related issues been closed when resolved?
Your Codemates team used Pull Requests to discuss solutions (60%)
Did every team member commit to the Pull Requests? (comments are not commits)
Specifically, I'm looking for a commit on each recipe from each team member. 
Did the team use the reviews feature of GitHub to get explicit approval? 
  You can use reviews or leave a comment in the Pull Request. Just have someone okay your change before merging!
Did at least TWO people approve each Pull Request? 
Work collaboratively on changes until objective is completed (10%)
Are there (2) fully completed recipes on the main/master branch?
Was there conversation, disagreement, discussion of style in the Pull Requests?

**Comment by TomPerticucci** [comment]
Thanks for adding this here. Let's ensure we tick all the requirements!

**Comment by TomPerticucci** [comment]
@D4V1DT4YL0R do you have any comments or commits that you want to make on the 2 recipes?
