### ISSUE TITLE
Adding a picture for both recipes?

### ISSUE THREAD

**Issue by TomPerticucci** [IntroToCode/CodeMates11_Fall22#6]
## 💬 Discussion topic

Picture for Ikea Meatballs

## ❗ Potential issues

Should we add a picture for the Ikea meatballs recipe as well? 

## 👥 People to consult

@Weisgit
@D4V1DT4YL0R
@ngocnguyen-angie
@Emora21

**Comment by Weisgit** [comment]
I'm taking care of the picture of our dinner recipe! Should be done in 1 minute!
